name: flutter_education_app
description: "A flutter portfolio project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.11.1

dependencies:
  bloc: ^9.2.0
  cloud_firestore: ^6.1.3
  connectivity_plus: ^7.0.0
  firebase_auth: ^6.2.0
  firebase_core: ^4.5.0
  firebase_database: ^12.1.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.3.1
  get: ^4.7.3
  google_fonts: ^8.0.2
  google_sign_in: ^7.2.0
  provider: ^6.1.5+1
  realtime_client: ^2.7.0
  riverpod: ^3.2.1
  sign_in_button: ^4.0.1
  supabase: ^2.10.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.local
    - .env.development
    - .env.production
    - assets/edumap-icon.png
    - assets/edumap-black-icon.png
    - assets/edumap-transparent-icon.png
    - assets/edumap-black-transparent-icon.png
